---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Root template for quicksight-frontend'

Parameters:
  TemplatePath:
    Description: S3Bucket Path where the templates are stored
    Type: String
    Default: ({})

  ProjectName:
    Description: A project name that is prefixed to resource names
    Type: String
    Default: ({})

  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    AllowedValues:
      - dev
      - prod
  
  SecurityStack:
    Description: The name of security cloudformation stack
    Type: String
    Default: ({})

  ArtifactsBucket:
    Description: The name of frontend pipeline artifact bucket
    Type: String
    Default: ({})

  FrontendBucket:
    Description: The name of frontend bucket
    Type: String
    Default: ({})
  
  GitHubAuthToken:
    Description: OAuthToken to connect to github
    Type: String
    Default: ({})
    NoEcho: true

Resources:
  CloudFrontStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/cft/frontend/cloudfront.yaml"
      Parameters:
        Environment: !Ref EnvironmentName
        S3BucketName: !Ref FrontendBucket
        CachePolicyName: !Sub ${ProjectName}-cache-policy-${EnvironmentName}
        CachePolicyGzip: 'true'
      Tags:
        - Key: Name
          Value: CloudFrontStack
    
  CodepipelineStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: CloudFrontStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/cft/pipeline.yaml"
      Parameters:
        Environment:  !Ref EnvironmentName
        GitHubAuthToken: !Ref GitHubAuthToken
        RepoName: 'Quicksight-Key-Metrics'
        ArtifactsBucket: !Ref ArtifactsBucket
        S3BucketName: !Ref FrontendBucket
        CloudFrontId: !GetAtt CloudFrontStack.Outputs.CloudFrontId
        SecurityStack: !Ref SecurityStack
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Name
          Value: CodepipelineStack

  NotificationStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: CodepipelineStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/cft/notification.yaml"
      Parameters:
        Environment: !Ref EnvironmentName
        PipelineStack: !GetAtt CodepipelineStack.Outputs.StackName
        SecurityStack: !Ref SecurityStack
        TemplatePath: !Ref TemplatePath
      Tags:
        - Key: Name
          Value: NotificationStack