---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Root template for quicksight-frontend'

Parameters:
  TemplatePath:
    Description: S3Bucket Path where the templates are stored
    Type: String
    Default: ({})

  ProjectName:
    Description: A project name that is prefixed to resource names
    Type: String
    Default: ({})

  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    AllowedValues:
      - dev
      - prod
  
  SecurityStack:
    Description: The name of security cloudformation stack
    Type: String
    Default: ({})

  ArtifactsBucket:
    Description: The name of frontend pipeline artifact bucket
    Type: String
    Default: ({})

  FrontendBucket:
    Description: The name of frontend bucket
    Type: String
    Default: ({})
  
  GitHubAuthToken:
    Description: OAuthToken to connect to github
    Type: String
    Default: ({})
    NoEcho: true

<<<<<<<< HEAD:root.yaml
========
  CICD:
    Description: Would you like A CI/CD process
    Type: String
    Default: ({})
    AllowedValues:
      - Yes
      - No

Conditions:
  Pipeline: !Equals [ !Ref CICD, Yes ]

>>>>>>>> parent of 056e84c (updates):frontend/root.yaml
Resources:
  CloudFrontStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/cft/frontend/cloudfront.yaml"
      Parameters:
        Environment: !Ref EnvironmentName
        S3BucketName: !Ref FrontendBucket
        CachePolicyName: !Sub ${ProjectName}-cache-policy-${EnvironmentName}
        CachePolicyGzip: 'true'
      Tags:
        - Key: Name
          Value: CloudFrontStack
    
<<<<<<<< HEAD:root.yaml
  CodepipelineStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: CloudFrontStack
========
  CodePipelineStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: CloudFrontStack
    Condition: Pipeline
>>>>>>>> parent of 056e84c (updates):frontend/root.yaml
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/cft/frontend/pipeline.yaml"
      Parameters:
        Environment:  !Ref EnvironmentName
        GitHubAuthToken: !Ref GitHubAuthToken
        RepoName: 'Quicksight-Key-Metrics'
        ArtifactsBucket: !Ref ArtifactsBucket
        S3BucketName: !Ref FrontendBucket
        CloudFrontId: !GetAtt CloudFrontStack.Outputs.CloudFrontId
        SecurityStack: !Ref SecurityStack
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Name
          Value: CodepipelineStack

  NotificationStack:
    Type: "AWS::CloudFormation::Stack"
<<<<<<<< HEAD:root.yaml
    DependsOn: CodepipelineStack
========
    DependsOn: CodePipelineStack
>>>>>>>> parent of 056e84c (updates):frontend/root.yaml
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatePath}/cft/frontend/notification.yaml"
      Parameters:
        Environment: !Ref EnvironmentName
        PipelineStack: !GetAtt CodepipelineStack.Outputs.StackName
        SecurityStack: !Ref SecurityStack
        TemplatePath: !Ref TemplatePath
      Tags:
        - Key: Name
          Value: NotificationStack